### ISSUE TITLE
Whats the function thats holds the image url payload?

### ISSUE THREAD

**Issue by RudyJessop** [DropsOfSerenity/react-avatar-cropper#10]
I am trying to figure out what function holds and manages the url payload of the image the user uploads.
![screen shot 2016-01-24 at 7 34 00 pm](https://cloud.githubusercontent.com/assets/700851/12540150/82fbc874-c2d1-11e5-8e81-e640661b7a1e.png)

End Output:
I want to save the image file the user uploads.

What I assume:
```
 prepareImage (imageUri) {
    var img = new Image();
    if (!isDataURL(imageUri)) img.crossOrigin = 'anonymous';
    img.onload = () => {
      var scaledImage = this.fitImageToCanvas(img.width, img.height);
      scaledImage.resource = img;
      scaledImage.x = 0;
      scaledImage.y = 0;
      this.setState({dragging: false, image: scaledImage, preview: this.toDataURL()});
    };
    img.src = imageUri;
  }
```
The code above is what I found in `AvatarCropper` module which i assume holds the entire url payload.

Let me know if I'm on the right track

**Comment by DropsOfSerenity** [comment]
Yeah the original image is passed in through the props. AvatarCropper.props.image is the users original image, whether that's a data uri or a url. AvatarCropper then fits the image to the canvas and stores the scaled image to state.

My recommendation would be to capture the users image upload before handing it off to avatar cropper if you wanted to store it. Similar to how facebook does it when a user drags an image into their cropper first they upload it to their servers, then they open the cropper with the uploaded image.

@RudyJessop Does this help?

**Comment by RudyJessop** [comment]
@DropsOfSerenity It 50% does. I want to save the users cropped image.

**Comment by DropsOfSerenity** [comment]
@RudyJessop You'll notice in the example application, I use the `onCrop` prop for `AvatarCropper` to give it the function to call when cropping is complete. This function receives the cropped data uri.

See the following:

https://github.com/DropsOfSerenity/react-avatar-cropper/blob/master/example/src/index.js#L47
https://github.com/DropsOfSerenity/react-avatar-cropper/blob/master/example/src/index.js#L20
https://github.com/DropsOfSerenity/react-avatar-cropper/blob/master/example/src/index.js#L41

**Comment by RudyJessop** [comment]
Nice 👍
Im guessing your built it for users to add their own uploading method?

**Comment by DropsOfSerenity** [comment]
Precisely, the cropper just hands back the data uri to send wherever you want :)

**Comment by RudyJessop** [comment]
Solid 👍

**Comment by RudyJessop** [comment]
@DropsOfSerenity hopefully you can shead some light on an issue I'm having with uploading the croppedImg via ajax. My addition can he viewed [here](https://gist.github.com/RudyJessop/0594557384810e2967389aac02516e27#file-app-js-L28) and [here](https://gist.github.com/RudyJessop/0594557384810e2967389aac02516e27#file-app-js-L30-L61) 

The error I'm getting is:
```
[2016-05-24 18:39:20] local.ERROR: exception 'ErrorException' with message 'Argument 1 passed to App\UsersPhotos::UserProfilePicture() must be an instance of Symfony\Component\HttpFoundation\File\UploadedFile, null given
```
On the browser console the image key is there but not passing through the request.

Thoughts?
