### ISSUE TITLE
Browserify Failed!: Cannot find module 'reactify'

### ISSUE THREAD

**Issue by RudyJessop** [DropsOfSerenity/react-avatar-cropper#3]
I'm incorporating this tool into a laravel project and when i run `gulp` i get the error `Browserify Failed!: Cannot find module 'reactify' from '<project_path>/node_modules/react-avatar-cropper'` What should be the solution. 

Also i noticed `node_modules` folder is missing. Certain the problem stems from this. 

PS: I ran `npm update react-avatar-cropper` and `npm install react-avatar-cropper` no success

**Comment by DropsOfSerenity** [comment]
@RudyJessop Hmm looks like I had some leftover junk in my `package.json` i've published a new version of `react-avatar-cropper` version 0.0.5, should work, try now.

**Comment by RudyJessop** [comment]
getting a different error. `rowserify Failed!: Cannot find module 'react-bootstrap' <project_path>/node_modules/react-avatar-cropper/dist`, 

One thing i did notice is that the `node_module` folder is missing.

**Comment by DropsOfSerenity** [comment]
@RudyJessop I think it's because react-bootstrap was not in dependencies, I've added it to dependencies in version 0.0.6. Give it a try now.

**Comment by RudyJessop** [comment]
Solid :)  works like a charm. expect a pull request in a couple days

**Comment by DropsOfSerenity** [comment]
Sounds good, glad it's working for ya :) my next task is to depend on the most recent react-bootstrap, but some syntax changed and I probably won't have time until the weekend hits.

Appreciate the github issues :)
