### ISSUE TITLE
compatibility with react 0.14

### ISSUE THREAD

**Issue by mauriyouth** [DropsOfSerenity/react-avatar-cropper#5]
Hello, 

dependency on react/lib/warning, breaks with react 0.14 :(

**Comment by DropsOfSerenity** [comment]
@mauriyouth Thanks, I'll look into it as soon as I have some spare time :)

**Comment by jesalg** [comment]
+1

**Comment by DropsOfSerenity** [comment]
Tested with react 0.14, believe this is working now. Please open another ticket if it's still not working for you.
